// Stage-based editorial guidance, not a pest forecast or pesticide prescription.
export const cropCare=[
 {focus:'다음 작기 준비',work:['전정과 유인 구조 정비','상자 배수·관수 설비 점검'],watch:['잔재물과 하우스 주변 잡초 확인','가지·잎의 이상 흔적 기록'],action:'잔재물을 정리하고 이상 부위는 사진으로 기록해 다음 생육기와 비교합니다.'},
 {focus:'발아와 초기 생육',work:['발아 균일도와 저온 피해 점검','신초 상태에 맞춰 관수 확인'],watch:['새눈과 어린잎의 변색·손상 확인','발아 이후 온도·습도 확인'],action:'발아 지연이나 손상이 있으면 온도·관수 기록을 함께 확인합니다.'},
 {focus:'수형과 착과 기반',work:['유인과 수관 내부 채광 확보','웃자람과 질소 공급 점검'],watch:['응애·총채벌레 예찰','잎과 어린 과실의 이상 확인'],action:'이상 부위와 주변 주를 함께 확인하고 하우스 내외 잡초를 정리합니다.'},
 {focus:'과실 비대와 수분 균형',work:['착과 상태와 고온 관리','급격한 수분 변화와 배수 점검'],watch:['응애·총채벌레 예찰','열과와 어린 과실 낙과 확인'],action:'잎·과실을 관찰하고 발생 위치를 기록합니다. 환기와 관수 상태도 함께 점검합니다.'},
 {focus:'착색과 품질 확보',work:['수관 채광과 고온 관리','과실 품질과 수분 변화 확인'],watch:['응애·총채벌레·초파리 예찰','열과·부패·병반 의심 부위 확인'],action:'손상 과실을 구분하고 병반은 사진으로 남겨 원인 확인 후 대응합니다.'},
 {focus:'수확과 출하 관리',work:['성숙도에 따른 수확·선별','낮은 과실 온도에서 수확하고 예냉'],watch:['수확기 해충과 손상 과실 확인','저장·출하 과정의 품질 점검'],action:'수확 직후 품질을 확인하고 예냉·저온 유통 상태를 점검합니다.'}
];
export function renderCropCare(index,month){const c=cropCare[index];return `<section class="panel crop-care"><div class="panel-head"><div><p class="care-kicker">CROP MANAGEMENT</p><h2>${month}월 · 생육 관리 및 병해충 점검</h2></div><span class="badge">생육 단계별 참고</span></div><p class="care-focus">${c.focus}</p><div class="care-grid"><article><span class="care-label">01 / 재배 관리</span><h3>이번 단계의 주요 작업</h3><ul>${c.work.map(t=>`<li>${t}</li>`).join('')}</ul></article><article><span class="care-label">02 / 병해충 · 생리장해</span><h3>현장에서 살펴볼 항목</h3><ul>${c.watch.map(t=>`<li>${t}</li>`).join('')}</ul></article></div><div class="care-response"><strong>이상 발견 시 대응</strong><p>${c.action}</p><p>약제 사용 전 <a href="https://psis.rda.go.kr/" target="_blank" rel="noopener">농약안전정보시스템 ↗</a>에서 무화과·대상 병해충의 등록 여부와 수확 전 사용 시기·횟수를 확인하세요.</p></div><p class="help">월별 단계는 화면 예시입니다. 겨울 가온재배에서는 실제 생육 상태와 가온 일정에 맞춰 참고하세요. 병해충 발생 예측이나 진단 결과는 아닙니다.</p><details class="care-source"><summary>관리 자료의 출처 · 적용 범위</summary><p>농촌진흥청 <a href="https://www.nongsaro.go.kr/portal/ps/psb/psbl/workScheduleDtl.ps?cntntsNo=30660&amp;menuId=PS00087" target="_blank" rel="noopener">농사로 — 무화과(무가온 시설재배) ↗</a>의 관리 항목을 참고해 화면용으로 재구성했습니다. 무가온 재배 자료의 달력을 겨울 가온재배에 그대로 적용하지 않습니다. 병반 사진 기록·설비 점검은 앱의 일반 점검 제안입니다. 자료 확인: 2026-10-05. 원문: 공공누리 제2유형(출처표시·상업적 이용금지).</p></details></section>`}
