import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';

const SAMPLE={"영암권(목포 대리지점)":{10:620,11:2680,12:5850,1:7420,2:6150,3:3720},"나주권(광주 대리지점)":{10:780,11:2950,12:6420,1:8010,2:6740,3:4050},"해남":{10:560,11:2480,12:5380,1:6900,2:5650,3:3420},"목포":{10:510,11:2320,12:4980,1:6350,2:5260,3:3180}};
let weatherRows=[],lastMonthly=[]; const $=id=>document.getElementById(id); const num=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f; const fmt=(v,d=0)=>new Intl.NumberFormat('ko-KR',{maximumFractionDigits:d,minimumFractionDigits:d}).format(v);
function inputs(){return{region:$('region').value,width:num($('width').value,7),length:num($('length').value,100),sideHeight:num($('sideHeight').value,2.5),ridgeHeight:num($('ridgeHeight').value,5),spanCount:Math.max(1,Math.round(num($('spanCount').value,1))),targetTemp:num($('targetTemp').value,12),coverU:num($('cover').value,4.1),curtainFactor:num($('curtain').value,.55),efficiency:num($('efficiency').value,1),price:num($('price').value,53)}}
function area(i){const totalW=i.width*i.spanCount,roof=Math.sqrt((i.width/2)**2+(i.ridgeHeight-i.sideHeight)**2);return 2*i.length*roof*i.spanCount+2*i.length*i.sideHeight+2*totalW*(i.sideHeight+(i.ridgeHeight-i.sideHeight)/2)}
function calcDegree(d,i){const a=area(i),u=i.coverU*i.curtainFactor;return[10,11,12,1,2,3].map(month=>{const dh=d[month]||0,load=a*u*dh/1000;return{month,hours:null,degreeHours:dh,loadKwh:load,cost:load/Math.max(i.efficiency,.01)*i.price}})}
function calcWeather(i){const g=new Map();for(const r of weatherRows){if(r.region&&r.region!==i.region)continue;if(![10,11,12,1,2,3].includes(r.month))continue;const x=g.get(r.month)||{degreeHours:0,hours:0};x.degreeHours+=Math.max(i.targetTemp-r.ta,0);x.hours++;g.set(r.month,x)}const a=area(i),u=i.coverU*i.curtainFactor;return[10,11,12,1,2,3].map(month=>{const x=g.get(month)||{degreeHours:0,hours:0},load=a*u*x.degreeHours/1000;return{month,hours:x.hours,degreeHours:x.degreeHours,loadKwh:load,cost:load/Math.max(i.efficiency,.01)*i.price}})}
function parseCsv(t){const l=t.trim().split(/\r?\n/).filter(Boolean),h=l[0].split(',').map(x=>x.trim().replace(/^\uFEFF/,''));return l.slice(1).map(x=>Object.fromEntries(h.map((k,j)=>[k,(x.split(',')[j]||'').trim()])))}
function normalize(rows){return rows.map(r=>{const tm=r.tm||r.date||r.datetime||'';return{month:num(r.month,tm?num(tm.slice(5,7),NaN):NaN),ta:num(r.ta_c||r.ta||r.temperature||r.temp,NaN),region:r.region||r.stn_name_kma||r.stn_name||''}}).filter(r=>Number.isFinite(r.month)&&Number.isFinite(r.ta))}

const holder=$('greenhouse3d'),scene=new THREE.Scene();scene.background=new THREE.Color(0xeaf4f3);const camera=new THREE.PerspectiveCamera(42,1,.1,1000);const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;holder.appendChild(renderer.domElement);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.target.set(0,2,0);scene.add(new THREE.HemisphereLight(0xffffff,0x71806d,2.2));const sun=new THREE.DirectionalLight(0xffffff,2.2);sun.position.set(20,30,15);sun.castShadow=true;scene.add(sun);const ground=new THREE.Mesh(new THREE.PlaneGeometry(300,300),new THREE.MeshStandardMaterial({color:0xdde8d9,roughness:1}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;scene.add(ground);let greenhouse=new THREE.Group();scene.add(greenhouse);
function tube(a,b,r=.035,mat){const d=new THREE.Vector3().subVectors(b,a),m=new THREE.Mesh(new THREE.CylinderGeometry(r,r,d.length(),8),mat);m.position.copy(a).add(b).multiplyScalar(.5);m.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),d.clone().normalize());return m}
function profilePoints(i,x0){const pts=[];pts.push(new THREE.Vector3(x0,0,0),new THREE.Vector3(x0,i.sideHeight,0));const n=12;for(let k=0;k<=n;k++){const t=k/n*Math.PI, x=x0+i.width/2+(i.width/2)*Math.cos(Math.PI-t), y=i.sideHeight+(i.ridgeHeight-i.sideHeight)*Math.sin(t);pts.push(new THREE.Vector3(x,y,0))}pts.push(new THREE.Vector3(x0+i.width,0,0));return pts}
function rebuild3d(i){scene.remove(greenhouse);greenhouse=new THREE.Group();const steel=new THREE.MeshStandardMaterial({color:0x60736a,metalness:.65,roughness:.35});const cover=new THREE.MeshPhysicalMaterial({color:0xd8f0e6,transparent:true,opacity:.22,side:THREE.DoubleSide,roughness:.2,metalness:0});const totalW=i.width*i.spanCount,L=Math.min(i.length,120);const zSteps=Math.max(5,Math.min(16,Math.round(L/7)));for(let s=0;s<i.spanCount;s++){const x0=-totalW/2+s*i.width;for(let zi=0;zi<=zSteps;zi++){const z=-L/2+L*zi/zSteps,p=profilePoints(i,x0);for(let k=0;k<p.length-1;k++){const a=p[k].clone();a.z=z;const b=p[k+1].clone();b.z=z;greenhouse.add(tube(a,b,.035,steel))}}const roofN=18;for(let k=0;k<=roofN;k++){const t=k/roofN*Math.PI,x=x0+i.width/2+(i.width/2)*Math.cos(Math.PI-t),y=i.sideHeight+(i.ridgeHeight-i.sideHeight)*Math.sin(t);greenhouse.add(tube(new THREE.Vector3(x,y,-L/2),new THREE.Vector3(x,y,L/2),.028,steel))}}
const shape=[];for(let s=0;s<i.spanCount;s++){const x0=-totalW/2+s*i.width;for(const p of profilePoints(i,x0))shape.push(p)}
for(let s=0;s<i.spanCount;s++){const x0=-totalW/2+s*i.width;const p=profilePoints(i,x0);const verts=[];for(let k=1;k<p.length-1;k++){const a=p[k],b=p[k+1];verts.push(a.x,a.y,-L/2,b.x,b.y,-L/2,a.x,a.y,L/2,b.x,b.y,-L/2,b.x,b.y,L/2,a.x,a.y,L/2)}const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(verts,3));geo.computeVertexNormals();greenhouse.add(new THREE.Mesh(geo,cover))}
scene.add(greenhouse);controls.target.set(0,i.ridgeHeight*.55,0);setView('perspective',i)}
function setView(v,i=inputs()){const W=i.width*i.spanCount,L=Math.min(i.length,120),d=Math.max(W,L*.55,i.ridgeHeight*5);if(v==='front')camera.position.set(0,i.ridgeHeight*.7,d*.72);else if(v==='side')camera.position.set(d*.72,i.ridgeHeight*.7,0);else if(v==='top')camera.position.set(.01,d*.9,.01);else camera.position.set(d*.58,d*.38,d*.62);camera.lookAt(0,i.ridgeHeight*.55,0);controls.update()}
function resize(){const w=holder.clientWidth,h=holder.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}new ResizeObserver(resize).observe(holder);function animate(){requestAnimationFrame(animate);controls.update();renderer.render(scene,camera)}animate();

function chart(monthly){const c=$('monthlyChart'),ctx=c.getContext('2d'),w=c.width,h=c.height;ctx.clearRect(0,0,w,h);ctx.fillStyle='#fff';ctx.fillRect(0,0,w,h);const p={left:65,right:25,top:24,bottom:42},cw=w-p.left-p.right,ch=h-p.top-p.bottom,max=Math.max(...monthly.map(r=>r.cost),1);ctx.font='14px Arial';for(let j=0;j<=4;j++){const y=p.top+ch/4*j;ctx.strokeStyle='#dce5df';ctx.beginPath();ctx.moveTo(p.left,y);ctx.lineTo(w-p.right,y);ctx.stroke();ctx.fillStyle='#65736d';ctx.fillText(`${fmt(max*(1-j/4)/10000)}만`,10,y+4)}const gap=22,bw=(cw-gap*(monthly.length-1))/monthly.length;monthly.forEach((r,k)=>{const x=p.left+k*(bw+gap),bh=r.cost/max*ch,y=p.top+ch-bh;ctx.fillStyle='#176b4d';ctx.fillRect(x,y,bw,bh);ctx.fillStyle='#14221d';ctx.textAlign='center';ctx.fillText(`${r.month}월`,x+bw/2,h-16)});ctx.textAlign='left'}
function render(){const i=inputs();$('targetTempLabel').textContent=`${i.targetTemp}°C`;const monthly=weatherRows.length?calcWeather(i):calcDegree(SAMPLE[i.region],i);lastMonthly=monthly;$('surfaceArea').textContent=`${fmt(area(i),1)} ㎡`;$('degreeHours').textContent=`${fmt(monthly.reduce((s,r)=>s+r.degreeHours,0))} ℃h`;$('loadKwh').textContent=`${fmt(monthly.reduce((s,r)=>s+r.loadKwh,0))} kWh`;$('cost').textContent=`${fmt(monthly.reduce((s,r)=>s+r.cost,0))} 원`;$('monthlyRows').innerHTML=monthly.map(r=>`<tr><td>${r.month}월</td><td>${r.hours===null?'예시':fmt(r.hours)}</td><td>${fmt(r.degreeHours)}</td><td>${fmt(r.loadKwh)}</td><td>${fmt(r.cost)}</td></tr>`).join('');$('dimWidth').textContent=`폭 ${fmt(i.width,1)} m × ${i.spanCount}연동`;$('dimLength').textContent=`길이 ${fmt(i.length,1)} m`;$('dimSide').textContent=`측고 ${fmt(i.sideHeight,1)} m`;$('dimRidge').textContent=`동고 ${fmt(i.ridgeHeight,1)} m`;$('dimSpan').textContent=`총 폭 ${fmt(i.width*i.spanCount,1)} m`;chart(monthly);rebuild3d(i)}
function download(){const h='month,valid_hours,heating_degree_hours,heating_load_kwh,estimated_cost_krw',rows=lastMonthly.map(r=>[r.month,r.hours??'',r.degreeHours.toFixed(3),r.loadKwh.toFixed(3),Math.round(r.cost)].join(',')),b=new Blob([[h,...rows].join('\n')],{type:'text/csv;charset=utf-8'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download='heating_cost_result_3d.csv';a.click();URL.revokeObjectURL(u)}
$('region').innerHTML=Object.keys(SAMPLE).map(r=>`<option>${r}</option>`).join('');document.querySelectorAll('input,select').forEach(el=>{if(el.type!=='file')el.addEventListener('input',render)});document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));$('resetButton').addEventListener('click',()=>{Object.assign($('width'),{value:7});$('length').value=100;$('sideHeight').value=2.5;$('ridgeHeight').value=5;$('spanCount').value=1;$('targetTemp').value=12;$('cover').value=4.1;$('curtain').value=.55;$('efficiency').value=1;$('price').value=53;weatherRows=[];$('dataStatus').textContent='예시 자료 사용 중';render()});$('downloadCsv').addEventListener('click',download);$('csvFile').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;weatherRows=normalize(parseCsv(await f.text()));$('dataStatus').textContent=`${fmt(weatherRows.length)}개 시간자료 사용 중`;render()});resize();render();