export const crops=[['rain','비가림 유지'],['extend','수확기 연장'],['early','조기 출하'],['winter','겨울 생산']];
export const sources=['가정값','농가 실적','현장 견적','참고자료'];
export const defaults=()=>({version:1,farmer:'existing',region:'전남',area:990,crop:'extend',budget:5000,baselineCash:900,baselineDep:100,ramp1:60,ramp2:85,ownLabor:300,fixed:180,labor:450,perKg:1800,loanPercent:30,interest:4,loanYears:5,investments:[{name:'시설 골조·피복',amount:2500,years:10,reuse:true},{name:'보온·가온 장비',amount:1800,years:8,reuse:false},{name:'양액·관수·재배 기반',amount:800,years:8,reuse:false},{name:'묘목·초기 조성',amount:400,years:8,reuse:true}],months:preset('extend'),ready:{water:false,power:false,drain:false,labor:false,skill:false,buyer:false},origins:{},notes:'',scenarios:[{name:'보수',yield:75,price:80,energy:125},{name:'기준',yield:100,price:100,energy:100},{name:'낙관',yield:110,price:110,energy:90}]});
export function preset(crop){const q={rain:[0,0,0,0,0,0,0,500,700,500,0,0],extend:[0,0,0,0,0,0,0,400,600,500,250,150],early:[0,0,0,0,0,150,300,450,500,300,0,0],winter:[180,140,0,0,0,0,0,250,450,350,200,180]}[crop];return q.map((kg,i)=>({kg,price:crop==='winter'&&(i<2||i>9)?18000:i===10||i===11?10000:6500,heat:crop==='rain'?0:crop==='extend'?(i>9?50:0):crop==='early'?(i<5?60:0):(i<2||i>9?180:0)}))}
export function validate(raw){if(!raw||raw.version!==1)throw Error('이 앱의 설정 파일(version 1)만 불러올 수 있습니다.');const s=defaults();for(const k of Object.keys(s))if(Object.hasOwn(raw,k))s[k]=raw[k];if(!['existing','new'].includes(s.farmer)||!crops.some(c=>c[0]===s.crop))throw Error('농가·작형을 확인하세요.');const ranges={area:[1,1000000],budget:[0,100000000],baselineCash:[-10000000,10000000],baselineDep:[0,10000000],ramp1:[0,150],ramp2:[0,150],ownLabor:[0,10000000],fixed:[0,10000000],labor:[0,10000000],perKg:[0,100000],loanPercent:[0,100],interest:[0,30],loanYears:[1,10]};for(const[k,[lo,hi]]of Object.entries(ranges))if(typeof s[k]!=='number'||!Number.isFinite(s[k])||s[k]<lo||s[k]>hi)throw Error(`${k} 입력 범위를 확인하세요.`);if(!Number.isInteger(s.loanYears))throw Error('상환기간은 정수입니다.');if(typeof s.region!=='string'||s.region.length>100||typeof s.notes!=='string'||s.notes.length>4000)throw Error('문구 길이를 확인하세요.');if(!Array.isArray(s.months)||s.months.length!==12)throw Error('월별 계획은 12개월이어야 합니다.');s.months=s.months.map(m=>{for(const[k,max]of [['kg',1000000],['price',1000000],['heat',10000000]])if(typeof m[k]!=='number'||!Number.isFinite(m[k])||m[k]<0||m[k]>max)throw Error('월별 수량·단가·난방비를 확인하세요.');return{kg:m.kg,price:m.price,heat:m.heat}});if(!Array.isArray(s.investments)||s.investments.length>30)throw Error('시설 항목은 최대 30개입니다.');s.investments=s.investments.map(r=>{if(typeof r.name!=='string'||r.name.length>100||!Number.isFinite(r.amount)||r.amount<0||r.amount>10000000||!Number.isFinite(r.years)||r.years<1||r.years>50||typeof r.reuse!=='boolean')throw Error('시설 입력을 확인하세요.');return{name:r.name,amount:r.amount,years:r.years,reuse:r.reuse}});if(!Array.isArray(s.scenarios)||s.scenarios.length!==3)throw Error('시나리오는 3개입니다.');s.scenarios=s.scenarios.map(r=>{if(typeof r.name!=='string'||r.name.length>30||['yield','price','energy'].some(k=>!Number.isFinite(r[k])||r[k]<0||r[k]>300))throw Error('시나리오 배율은 0~300%입니다.');return{name:r.name,yield:r.yield,price:r.price,energy:r.energy}});if(!s.ready||typeof s.ready!=='object'||Array.isArray(s.ready))throw Error('준비도 형식을 확인하세요.');s.ready=Object.fromEntries(['water','power','drain','labor','skill','buyer'].map(k=>[k,s.ready[k]===true]));if(!s.origins||typeof s.origins!=='object'||Array.isArray(s.origins)||Object.keys(s.origins).length>300)throw Error('입력 근거를 확인하세요.');s.origins=Object.fromEntries(Object.entries(s.origins).map(([k,v])=>{if(k.length>80||!sources.includes(v))throw Error('입력 근거를 확인하세요.');return[k,v]}));return s}
export function calculate(s,scenario={yield:100,price:100,energy:100}){const applied=s.investments.filter(r=>s.farmer==='new'||!r.reuse),investment=applied.reduce((n,r)=>n+r.amount,0),depreciation=applied.reduce((n,r)=>n+r.amount/r.years,0)+(s.farmer==='existing'?s.baselineDep:0),loan=investment*s.loanPercent/100,principal=loan/s.loanYears,baseCash=s.farmer==='existing'?s.baselineCash:0;const annual=[];let cumulative=-investment,balance=-(investment-loan),lowest=balance;
 for(let year=1;year<=10;year++){const ramp=year===1?s.ramp1/100:year===2?s.ramp2/100:1,rate=ramp*scenario.yield/100,interest=Math.max(0,loan-principal*(year-1))*s.interest/100,debt=year<=s.loanYears?principal:0;
 const months=s.months.map(m=>{const kg=m.kg*rate,revenue=kg*m.price*scenario.price/100/10000,variable=kg*s.perKg/10000,heating=m.heat*scenario.energy/100,cost=variable+heating+(s.fixed+s.labor)/12,operating=revenue-cost,equity=operating-interest/12-debt/12;return{kg,revenue,variable,heating,cost,operating,equity}});
 const sum=k=>months.reduce((n,m)=>n+m[k],0),cash=sum('operating'),profit=cash-depreciation-interest,fullProfit=profit-s.ownLabor,increment=cash-baseCash;cumulative+=increment;
 if(year===1)for(const m of months){balance+=m.equity;lowest=Math.min(lowest,balance);m.balance=balance}
 annual.push({year,ramp,months,revenue:sum('revenue'),kg:sum('kg'),heating:sum('heating'),cost:sum('cost'),cash,interest,debt,profit,fullProfit,increment,cumulative,equity:sum('equity')});}
 const first=annual[0],steady=annual[2],required=Math.max(0,-lowest),payback=investment===0?null:annual.find(a=>a.cumulative>=0)?.year||null;return{investment,depreciation,loan,first,steady,annual,required,gap:Math.max(0,required-s.budget),payback,baseCash,breakEvenPrice:steady.kg>0?(steady.cost+depreciation+steady.interest+s.ownLabor)*10000/steady.kg:null};}
